### ISSUE TITLE
Compatibility issue in merging depth dataframes

### ISSUE THREAD

**Issue by ftbernales** [ftbernales/Deepsoil-Compile#9]
```
Traceback (most recent call last):
  File "[USER]\Documents\Projects\Deepsoil-Compile\src\Deepsoil_Compile.py", line 309, in <module>
    main()
  File "[USER]\Documents\Projects\Deepsoil-Compile\src\Deepsoil_Compile.py", line 218, in main
    df_next_strain_comb = pd.merge_asof(df_depths,
  File "[USER]\.conda\envs\deepsoil\lib\site-packages\pandas\core\reshape\merge.py", line 581, in merge_asof
    op = _AsOfMerge(
  File "[USER]\.conda\envs\deepsoil\lib\site-packages\pandas\core\reshape\merge.py", line 1744, in __init__
    _OrderedMerge.__init__(
  File "[USER]\.conda\envs\deepsoil\lib\site-packages\pandas\core\reshape\merge.py", line 1630, in __init__
    _MergeOperation.__init__(
  File "[USER]\.conda\envs\deepsoil\lib\site-packages\pandas\core\reshape\merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "[USER]\.conda\envs\deepsoil\lib\site-packages\pandas\core\reshape\merge.py", line 1862, in _get_merge_keys
    raise MergeError(msg)
pandas.errors.MergeError: incompatible merge keys [0] dtype('float64') and dtype('int64'), must be the same type
```

**Comment by ftbernales** [comment]
`DEPTH_LAYER` and `DEPTH_LAYER_MID` must be ensured to be `float` 

https://github.com/ftbernales/Deepsoil-Compile/blob/e2eb77d5610bfa8729e9cfa92e54c69f0abf2b45/src/Deepsoil_Compile.py#L207-L222

**Comment by ftbernales** [comment]
Finding: Exact `DEPTH_LAYER` and `DEPTH_LAYER_MID` values becomes `int` because Excel neglects trailing decimal zeros:

https://github.com/ftbernales/Deepsoil-Compile/blob/e2eb77d5610bfa8729e9cfa92e54c69f0abf2b45/src/Deepsoil_Compile.py#L208
